# Generated by Django 5.2.13 on 2026-05-26 05:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=200)),
                ('icd_code', models.CharField(blank=True, help_text='ICD-10 classification code', max_length=20)),
                ('diagnosed_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Resolved', 'Resolved')], default='Active', max_length=50)),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Moderate', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-diagnosed_date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g., 500mg', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., Once daily', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('refills_remaining', models.IntegerField(default=0)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure_sys', models.IntegerField(blank=True, help_text='Systolic (mmHg)', null=True)),
                ('blood_pressure_dia', models.IntegerField(blank=True, help_text='Diastolic (mmHg)', null=True)),
                ('heart_rate_bpm', models.IntegerField(blank=True, help_text='Heart rate (bpm)', null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature (°C)', max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vitals',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
