# Generated by Django 5.2.13 on 2026-04-24 11:57

import django.db.models.deletion
import sharing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_type_record_record_type_remove_record_date_and_more'),
        ('sharing', '0003_alter_sharetoken_expires_at_alter_sharetoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharetoken',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='records.record'),
        ),
        migrations.AlterField(
            model_name='sharetoken',
            name='token',
            field=models.CharField(db_index=True, default=sharing.models.generate_secure_token, max_length=64, unique=True),
        ),
    ]
